const voices = [
  {
    id: 1,
    voice: 'Hala',
    voiceGender: 'Female',
    language: 'ar-AE',
    languageDescription: 'Gulf Arabic',
    engine: 'neural',
  },
  {
    id: 2,
    voice: 'Zayd',
    voiceGender: 'Male',
    language: 'ar-AE',
    languageDescription: 'Gulf Arabic',
    engine: 'neural',
  },
  {
    id: 3,
    voice: 'Hala',
    voiceGender: 'Female',
    language: 'arb',
    languageDescription: 'Gulf Arabic',
    engine: 'neural',
  },
  {
    id: 4,
    voice: 'Zayd',
    voiceGender: 'Male',
    language: 'arb',
    languageDescription: 'Gulf Arabic',
    engine: 'neural',
  },
  {
    id: 5,
    voice: 'Zeina',
    voiceGender: 'Female',
    language: 'arb',
    languageDescription: 'Arabic',
    engine: 'standard',
  },
  {
    id: 6,
    voice: 'Arlet',
    voiceGender: 'Female',
    language: 'ca-ES',
    languageDescription: 'Catalan',
    engine: 'neural',
  },
  {
    id: 7,
    voice: 'Zhiyu',
    voiceGender: 'Female',
    language: 'cmn-CN',
    languageDescription: 'Chinese Mandarin',
    engine: 'neural',
  },
  {
    id: 8,
    voice: 'Zhiyu',
    voiceGender: 'Female',
    language: 'cmn-CN',
    languageDescription: 'Chinese Mandarin',
    engine: 'standard',
  },
  {
    id: 9,
    voice: 'Jitka',
    voiceGender: 'Female',
    language: 'cs-CZ',
    languageDescription: 'Czech',
    engine: 'neural',
  },
  {
    id: 10,
    voice: 'Gwyneth',
    voiceGender: 'Female',
    language: 'cy-GB',
    languageDescription: 'Welsh',
    engine: 'standard',
  },
  {
    id: 11,
    voice: 'Mads',
    voiceGender: 'Male',
    language: 'da-DK',
    languageDescription: 'Danish',
    engine: 'standard',
  },
  {
    id: 12,
    voice: 'Naja',
    voiceGender: 'Female',
    language: 'da-DK',
    languageDescription: 'Danish',
    engine: 'standard',
  },
  {
    id: 13,
    voice: 'Sofie',
    voiceGender: 'Female',
    language: 'da-DK',
    languageDescription: 'Danish',
    engine: 'neural',
  },
  {
    id: 14,
    voice: 'Hannah',
    voiceGender: 'Female',
    language: 'de-AT',
    languageDescription: 'Austrian German',
    engine: 'neural',
  },
  {
    id: 15,
    voice: 'Sabrina',
    voiceGender: 'Female',
    language: 'de-CH',
    languageDescription: 'Swiss Standard German',
    engine: 'neural',
  },
  {
    id: 16,
    voice: 'Daniel',
    voiceGender: 'Male',
    language: 'de-DE',
    languageDescription: 'German',
    engine: 'neural',
  },
  {
    id: 17,
    voice: 'Hans',
    voiceGender: 'Male',
    language: 'de-DE',
    languageDescription: 'German',
    engine: 'standard',
  },
  {
    id: 18,
    voice: 'Marlene',
    voiceGender: 'Female',
    language: 'de-DE',
    languageDescription: 'German',
    engine: 'standard',
  },
  {
    id: 19,
    voice: 'Vicki',
    voiceGender: 'Female',
    language: 'de-DE',
    languageDescription: 'German',
    engine: 'neural',
  },
  {
    id: 20,
    voice: 'Vicki',
    voiceGender: 'Female',
    language: 'de-DE',
    languageDescription: 'German',
    engine: 'standard',
  },
  {
    id: 21,
    voice: 'Nicole',
    voiceGender: 'Female',
    language: 'en-AU',
    languageDescription: 'Australian English',
    engine: 'standard',
  },
  {
    id: 22,
    voice: 'Olivia',
    voiceGender: 'Female',
    language: 'en-AU',
    languageDescription: 'Australian English',
    engine: 'neural',
  },
  {
    id: 23,
    voice: 'Russell',
    voiceGender: 'Male',
    language: 'en-AU',
    languageDescription: 'Australian English',
    engine: 'standard',
  },
  {
    id: 24,
    voice: 'Amy',
    voiceGender: 'Female',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'generative',
  },
  {
    id: 25,
    voice: 'Amy',
    voiceGender: 'Female',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'neural',
  },
  {
    id: 26,
    voice: 'Amy',
    voiceGender: 'Female',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'standard',
  },
  {
    id: 27,
    voice: 'Arthur',
    voiceGender: 'Male',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'neural',
  },
  {
    id: 28,
    voice: 'Brian',
    voiceGender: 'Male',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'neural',
  },
  {
    id: 29,
    voice: 'Brian',
    voiceGender: 'Male',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'standard',
  },
  {
    id: 30,
    voice: 'Emma',
    voiceGender: 'Female',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'neural',
  },
  {
    id: 31,
    voice: 'Emma',
    voiceGender: 'Female',
    language: 'en-GB',
    languageDescription: 'British English',
    engine: 'standard',
  },
  {
    id: 32,
    voice: 'Geraint',
    voiceGender: 'Male',
    language: 'en-GB-WLS',
    languageDescription: 'Welsh English',
    engine: 'standard',
  },
  {
    id: 33,
    voice: 'Niamh',
    voiceGender: 'Female',
    language: 'en-IE',
    languageDescription: 'Irish English',
    engine: 'neural',
  },
  {
    id: 34,
    voice: 'Aditi',
    voiceGender: 'Female',
    language: 'en-IN',
    languageDescription: 'Indian English',
    engine: 'standard',
  },
  {
    id: 35,
    voice: 'Kajal',
    voiceGender: 'Female',
    language: 'en-IN',
    languageDescription: 'Indian English',
    engine: 'neural',
  },
  {
    id: 36,
    voice: 'Raveena',
    voiceGender: 'Female',
    language: 'en-IN',
    languageDescription: 'Indian English',
    engine: 'standard',
  },
  {
    id: 37,
    voice: 'Aria',
    voiceGender: 'Female',
    language: 'en-NZ',
    languageDescription: 'New Zealand English',
    engine: 'neural',
  },
  {
    id: 38,
    voice: 'Danielle',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 39,
    voice: 'Gregory',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 40,
    voice: 'Ivy',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 41,
    voice: 'Ivy',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 42,
    voice: 'Joanna',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 43,
    voice: 'Joanna',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 44,
    voice: 'Joey',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 45,
    voice: 'Joey',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 46,
    voice: 'Justin',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 47,
    voice: 'Justin',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 48,
    voice: 'Kendra',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 49,
    voice: 'Kendra',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 50,
    voice: 'Kevin',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 51,
    voice: 'Kimberly',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 52,
    voice: 'Kimberly',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 53,
    voice: 'Matthew',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'generative',
  },
  {
    id: 54,
    voice: 'Matthew',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 55,
    voice: 'Matthew',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 56,
    voice: 'Ruth',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'generative',
  },
  {
    id: 57,
    voice: 'Ruth',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 58,
    voice: 'Salli',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 59,
    voice: 'Salli',
    voiceGender: 'Female',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'standard',
  },
  {
    id: 60,
    voice: 'Stephen',
    voiceGender: 'Male',
    language: 'en-US',
    languageDescription: 'US English',
    engine: 'neural',
  },
  {
    id: 61,
    voice: 'Ayanda',
    voiceGender: 'Female',
    language: 'en-ZA',
    languageDescription: 'South African English',
    engine: 'neural',
  },
  {
    id: 62,
    voice: 'Conchita',
    voiceGender: 'Female',
    language: 'es-ES',
    languageDescription: 'Castilian Spanish',
    engine: 'standard',
  },
  {
    id: 63,
    voice: 'Enrique',
    voiceGender: 'Male',
    language: 'es-ES',
    languageDescription: 'Castilian Spanish',
    engine: 'standard',
  },
  {
    id: 64,
    voice: 'Lucia',
    voiceGender: 'Female',
    language: 'es-ES',
    languageDescription: 'Castilian Spanish',
    engine: 'neural',
  },
  {
    id: 65,
    voice: 'Lucia',
    voiceGender: 'Female',
    language: 'es-ES',
    languageDescription: 'Castilian Spanish',
    engine: 'standard',
  },
  {
    id: 66,
    voice: 'Sergio',
    voiceGender: 'Male',
    language: 'es-ES',
    languageDescription: 'Castilian Spanish',
    engine: 'neural',
  },
  {
    id: 67,
    voice: 'Andres',
    voiceGender: 'Male',
    language: 'es-MX',
    languageDescription: 'Mexican Spanish',
    engine: 'neural',
  },
  {
    id: 68,
    voice: 'Mia',
    voiceGender: 'Female',
    language: 'es-MX',
    languageDescription: 'Mexican Spanish',
    engine: 'neural',
  },
  {
    id: 69,
    voice: 'Mia',
    voiceGender: 'Female',
    language: 'es-MX',
    languageDescription: 'Mexican Spanish',
    engine: 'standard',
  },
  {
    id: 70,
    voice: 'Lupe',
    voiceGender: 'Female',
    language: 'es-US',
    languageDescription: 'US Spanish',
    engine: 'neural',
  },
  {
    id: 71,
    voice: 'Lupe',
    voiceGender: 'Female',
    language: 'es-US',
    languageDescription: 'US Spanish',
    engine: 'standard',
  },
  {
    id: 72,
    voice: 'Miguel',
    voiceGender: 'Male',
    language: 'es-US',
    languageDescription: 'US Spanish',
    engine: 'standard',
  },
  {
    id: 73,
    voice: 'Pedro',
    voiceGender: 'Male',
    language: 'es-US',
    languageDescription: 'US Spanish',
    engine: 'neural',
  },
  {
    id: 74,
    voice: 'Penelope',
    voiceGender: 'Female',
    language: 'es-US',
    languageDescription: 'US Spanish',
    engine: 'standard',
  },
  {
    id: 75,
    voice: 'Suvi',
    voiceGender: 'Female',
    language: 'fi-FI',
    languageDescription: 'Finnish',
    engine: 'neural',
  },
  {
    id: 76,
    voice: 'Isabelle',
    voiceGender: 'Female',
    language: 'fr-BE',
    languageDescription: 'Belgian French',
    engine: 'neural',
  },
  {
    id: 77,
    voice: 'Chantal',
    voiceGender: 'Female',
    language: 'fr-CA',
    languageDescription: 'Canadian French',
    engine: 'standard',
  },
  {
    id: 78,
    voice: 'Gabrielle',
    voiceGender: 'Female',
    language: 'fr-CA',
    languageDescription: 'Canadian French',
    engine: 'neural',
  },
  {
    id: 79,
    voice: 'Liam',
    voiceGender: 'Male',
    language: 'fr-CA',
    languageDescription: 'Canadian French',
    engine: 'neural',
  },
  {
    id: 80,
    voice: 'Celine',
    voiceGender: 'Female',
    language: 'fr-FR',
    languageDescription: 'French',
    engine: 'standard',
  },
  {
    id: 81,
    voice: 'Lea',
    voiceGender: 'Female',
    language: 'fr-FR',
    languageDescription: 'French',
    engine: 'neural',
  },
  {
    id: 82,
    voice: 'Lea',
    voiceGender: 'Female',
    language: 'fr-FR',
    languageDescription: 'French',
    engine: 'standard',
  },
  {
    id: 83,
    voice: 'Mathieu',
    voiceGender: 'Male',
    language: 'fr-FR',
    languageDescription: 'French',
    engine: 'standard',
  },
  {
    id: 84,
    voice: 'Remi',
    voiceGender: 'Male',
    language: 'fr-FR',
    languageDescription: 'French',
    engine: 'neural',
  },
  {
    id: 85,
    voice: 'Aditi',
    voiceGender: 'Female',
    language: 'hi-IN',
    languageDescription: 'Indian English',
    engine: 'standard',
  },
  {
    id: 86,
    voice: 'Kajal',
    voiceGender: 'Female',
    language: 'hi-IN',
    languageDescription: 'Indian English',
    engine: 'neural',
  },
  {
    id: 87,
    voice: 'Dora',
    voiceGender: 'Female',
    language: 'is-IS',
    languageDescription: 'Icelandic',
    engine: 'standard',
  },
  {
    id: 88,
    voice: 'Karl',
    voiceGender: 'Male',
    language: 'is-IS',
    languageDescription: 'Icelandic',
    engine: 'standard',
  },
  {
    id: 89,
    voice: 'Adriano',
    voiceGender: 'Male',
    language: 'it-IT',
    languageDescription: 'Italian',
    engine: 'neural',
  },
  {
    id: 90,
    voice: 'Bianca',
    voiceGender: 'Female',
    language: 'it-IT',
    languageDescription: 'Italian',
    engine: 'neural',
  },
  {
    id: 91,
    voice: 'Bianca',
    voiceGender: 'Female',
    language: 'it-IT',
    languageDescription: 'Italian',
    engine: 'standard',
  },
  {
    id: 92,
    voice: 'Carla',
    voiceGender: 'Female',
    language: 'it-IT',
    languageDescription: 'Italian',
    engine: 'standard',
  },
  {
    id: 93,
    voice: 'Giorgio',
    voiceGender: 'Male',
    language: 'it-IT',
    languageDescription: 'Italian',
    engine: 'standard',
  },
  {
    id: 94,
    voice: 'Kazuha',
    voiceGender: 'Female',
    language: 'ja-JP',
    languageDescription: 'Japanese',
    engine: 'neural',
  },
  {
    id: 95,
    voice: 'Mizuki',
    voiceGender: 'Female',
    language: 'ja-JP',
    languageDescription: 'Japanese',
    engine: 'standard',
  },
  {
    id: 96,
    voice: 'Takumi',
    voiceGender: 'Male',
    language: 'ja-JP',
    languageDescription: 'Japanese',
    engine: 'neural',
  },
  {
    id: 97,
    voice: 'Takumi',
    voiceGender: 'Male',
    language: 'ja-JP',
    languageDescription: 'Japanese',
    engine: 'standard',
  },
  {
    id: 98,
    voice: 'Tomoko',
    voiceGender: 'Female',
    language: 'ja-JP',
    languageDescription: 'Japanese',
    engine: 'neural',
  },
  {
    id: 99,
    voice: 'Seoyeon',
    voiceGender: 'Female',
    language: 'ko-KR',
    languageDescription: 'Korean',
    engine: 'neural',
  },
  {
    id: 100,
    voice: 'Seoyeon',
    voiceGender: 'Female',
    language: 'ko-KR',
    languageDescription: 'Korean',
    engine: 'standard',
  },
  {
    id: 101,
    voice: 'Ida',
    voiceGender: 'Female',
    language: 'nb-NO',
    languageDescription: 'Norwegian',
    engine: 'neural',
  },
  {
    id: 102,
    voice: 'Liv',
    voiceGender: 'Female',
    language: 'nb-NO',
    languageDescription: 'Norwegian',
    engine: 'standard',
  },
  {
    id: 103,
    voice: 'Lisa',
    voiceGender: 'Female',
    language: 'nl-BE',
    languageDescription: 'Belgian Dutch',
    engine: 'neural',
  },
  {
    id: 104,
    voice: 'Laura',
    voiceGender: 'Female',
    language: 'nl-NL',
    languageDescription: 'Dutch',
    engine: 'neural',
  },
  {
    id: 105,
    voice: 'Lotte',
    voiceGender: 'Female',
    language: 'nl-NL',
    languageDescription: 'Dutch',
    engine: 'standard',
  },
  {
    id: 106,
    voice: 'Ruben',
    voiceGender: 'Male',
    language: 'nl-NL',
    languageDescription: 'Dutch',
    engine: 'standard',
  },
  {
    id: 107,
    voice: 'Ewa',
    voiceGender: 'Female',
    language: 'pl-PL',
    languageDescription: 'Polish',
    engine: 'standard',
  },
  {
    id: 108,
    voice: 'Jacek',
    voiceGender: 'Male',
    language: 'pl-PL',
    languageDescription: 'Polish',
    engine: 'standard',
  },
  {
    id: 109,
    voice: 'Jan',
    voiceGender: 'Male',
    language: 'pl-PL',
    languageDescription: 'Polish',
    engine: 'standard',
  },
  {
    id: 110,
    voice: 'Maja',
    voiceGender: 'Female',
    language: 'pl-PL',
    languageDescription: 'Polish',
    engine: 'standard',
  },
  {
    id: 111,
    voice: 'Ola',
    voiceGender: 'Female',
    language: 'pl-PL',
    languageDescription: 'Polish',
    engine: 'neural',
  },
  {
    id: 112,
    voice: 'Camila',
    voiceGender: 'Female',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'neural',
  },
  {
    id: 113,
    voice: 'Camila',
    voiceGender: 'Female',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'standard',
  },
  {
    id: 114,
    voice: 'Ricardo',
    voiceGender: 'Male',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'standard',
  },
  {
    id: 115,
    voice: 'Thiago',
    voiceGender: 'Male',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'neural',
  },
  {
    id: 116,
    voice: 'Vitoria',
    voiceGender: 'Female',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'neural',
  },
  {
    id: 117,
    voice: 'Vitoria',
    voiceGender: 'Female',
    language: 'pt-BR',
    languageDescription: 'Brazilian Portuguese',
    engine: 'standard',
  },
  {
    id: 118,
    voice: 'Cristiano',
    voiceGender: 'Male',
    language: 'pt-PT',
    languageDescription: 'Portuguese',
    engine: 'standard',
  },
  {
    id: 119,
    voice: 'Ines',
    voiceGender: 'Female',
    language: 'pt-PT',
    languageDescription: 'Portuguese',
    engine: 'neural',
  },
  {
    id: 120,
    voice: 'Ines',
    voiceGender: 'Female',
    language: 'pt-PT',
    languageDescription: 'Portuguese',
    engine: 'standard',
  },
  {
    id: 121,
    voice: 'Carmen',
    voiceGender: 'Female',
    language: 'ro-RO',
    languageDescription: 'Romanian',
    engine: 'standard',
  },
  {
    id: 122,
    voice: 'Maxim',
    voiceGender: 'Male',
    language: 'ru-RU',
    languageDescription: 'Russian',
    engine: 'standard',
  },
  {
    id: 123,
    voice: 'Tatyana',
    voiceGender: 'Female',
    language: 'ru-RU',
    languageDescription: 'Russian',
    engine: 'standard',
  },
  {
    id: 124,
    voice: 'Astrid',
    voiceGender: 'Female',
    language: 'sv-SE',
    languageDescription: 'Swedish',
    engine: 'standard',
  },
  {
    id: 125,
    voice: 'Elin',
    voiceGender: 'Female',
    language: 'sv-SE',
    languageDescription: 'Swedish',
    engine: 'neural',
  },
  {
    id: 126,
    voice: 'Burcu',
    voiceGender: 'Female',
    language: 'tr-TR',
    languageDescription: 'Turkish',
    engine: 'neural',
  },
  {
    id: 127,
    voice: 'Filiz',
    voiceGender: 'Female',
    language: 'tr-TR',
    languageDescription: 'Turkish',
    engine: 'standard',
  },
  {
    id: 128,
    voice: 'Hiujin',
    voiceGender: 'Female',
    language: 'yue-CN',
    languageDescription: 'Cantonese',
    engine: 'neural',
  },
]

export default voices
